// This file is auto-generated by xulsword/setenv.
// This is a polyfill for part of Electron's 'process'
// object that will be used by NodeJS webapp server.
/* eslint-disable @typescript-eslint/naming-convention */
import type process from 'process';
export default {
  argv: [],
  env: {
    NODE_ENV: 'development',
    XULSWORD_ENV: 'normal',
    DEBUG_PROD: 'false',
    LOGLEVEL: 'debug',
    XSPORT: '3576',
  },
  platform: 'browser',
} as typeof process;
