#!/bin/bash
# Run this script from this directory with 'source ./setenv' to set build environment variables.

export LIBXULSWORD_MAJOR=1
export LIBXULSWORD_MINOR=5
export LIBXULSWORD_REVIS=6

if [ -e /vagrant ]; then export CONTEXT="guest"; else export CONTEXT="host"; fi
if [ "$CONTEXT" = "guest" ]; then export XULSWORD="$HOME/src/xulsword"; else export XULSWORD="$( pwd -P )"; fi
export CPP="$XULSWORD/Cpp"
export LIBXULSWORD="$XULSWORD/build/app/node_modules/libxulsword"

# Set WINMACHINE to x86 or x64 to compile Windows 32 bit or 64 bit, respectively:
export WINMACHINE=x86

export TOOLCHAIN_PREFIX=i686-w64-mingw32
export ADDRESS_MODEL=32
if [ "$WINMACHINE" = "x64" ]; then
  export ADDRESS_MODEL=64
  export TOOLCHAIN_PREFIX=x86_64-w64-mingw32
fi

export XCWD="${ADDRESS_MODEL}win"

# The ming-gcc cross-compiler standard must be 'posix' to work with NodeAPI:
export GCCSTD=posix
