#!/bin/bash

# Source this script so node-gyp will cross-compile.

if [[ "$1" == *"mingw32" ]]; then
  export GYP_CROSSCOMPILE=1
  export CC_target="/usr/bin/${TOOLCHAIN_PREFIX}-gcc-${GCCSTD}"
  export CXX_target="/usr/bin/${TOOLCHAIN_PREFIX}-g++-${GCCSTD}"
  export LD_target="/usr/bin/${TOOLCHAIN_PREFIX}-ld"
  export AR_target="/usr/bin/${TOOLCHAIN_PREFIX}-ar"
  export AS_target="/usr/bin/${TOOLCHAIN_PREFIX}-as"
  export GYP_SYSROOT="/usr/${TOOLCHAIN_PREFIX}"
else
  if [ -z $1 ]; then
    unset GYP_CROSSCOMPILE
    unset CC_target
    unset CXX_target
    unset LD_target
    unset AR_target
    unset AS_target
    unset GYP_SYSROOT
  fi
fi
