#!/bin/bash

# Source this script so node-gyp will cross-compile.

export GYP_CROSSCOMPILE=1

if [[ "$1" == *"mingw32" ]]; then
  export CC_target="/usr/bin/${TOOLCHAIN_PREFIX}-gcc-${GCCSTD}"
  export CXX_target="/usr/bin/${TOOLCHAIN_PREFIX}-g++-${GCCSTD}"
  export LD_target="/usr/bin/${TOOLCHAIN_PREFIX}-ld"
  export AR_target="/usr/bin/${TOOLCHAIN_PREFIX}-ar"
  export AS_target="/usr/bin/${TOOLCHAIN_PREFIX}-as"
  export GYP_SYSROOT="/usr/i686-w64-mingw32"
fi
