# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/dale/src/xulsword/Cpp/clucene.32win/build/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /home/dale/src/xulsword/Cpp/clucene.32win/build/CMakeFiles/cmTC_54330-_CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE.exe
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.16/Modules/CheckCXXSourceRuns.cmake
#                 [2]	/home/dale/src/xulsword/Cpp/clucene.32win/src/shared/cmake/CheckPthread.cmake
#                 [1]	/home/dale/src/xulsword/Cpp/clucene.32win/src/shared/CMakeLists.txt

set( _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE 
     "FAILED_TO_RUN"
     CACHE STRING "Result from TRY_RUN" FORCE)

set( _CL_HAVE_PTHREAD_MUTEX_RECURSIVE_EXITCODE__TRYRUN_OUTPUT 
     "NOTFOUND"
     CACHE STRING "Output from TRY_RUN" FORCE)

