#!/bin/bash
# Source this script from the current directory with 'source ./setenv' to
# properly set environment variables. Comments indicate each setting
# and the default value.

# Set the following variables to enable an SSL webapp server
# export SERVER_KEY_PEM=full-path-to-key-pem-file
# export SERVER_CRT_PEM=full-path-to-certificate-pem-file

# export WEBAPP_DOMAIN='http://localhost:1212'

# export WEBAPP_CORS_ORIGIN='http://localhost:1212'

# export WEBAPP_PORT=3576

# export WEBAPP_SERVERROOT_DIR=[xulsword]/profile_webapp/web

# Semicolon delimited list of public URLs relative to WEBAPP_SERVERROOT_DIR; each starting with slash.
# export WEBAPP_PUBPATHS=/

# The public URL on the web app server where webpacked files are served from (beginning and ending with slash).
# export WEBAPP_PUBLIC_DIST=/

# The full path to the private directory where web app files are written and read.
# export WEBAPP_PROFILE_DIR=[xulsword]/profile_webapp

# export WEBAPP_RESOURCE_DIR=[xulsword]/profile_webapp/web/resources

# export XSFonts_DIR=[xulsword]/profile_webapp/web/resources/fonts

# export XSModsUser_DIR=$WEBAPP_RESOURCE_DIR
export XSModsUser_DIR=~/.config/Electron/resources

# export XSModsCommon_DIR=$HOME/.sword

# export XSAudio_DIR=$WEBAPP_RESOURCE_DIR/audio

# export WEBPACK_DEV_WEBAPP_PORT=1212

# export WEBPACK_DEV_APP_PORT=1213

# export LOG_DIR=[xulsword]/profile_webapp

# export WEBAPP_MAX_CACHE_RAMMB=250

# export WEBAPP_SEARCH_BAN=2000

# export WEBAPP_SKIP_MODULES=

# export WEBAPP_MAX_LOG_SIZE=5000000

# export LOGLEVEL='error'

###############################################################################
# libxulsword Cpp build environment variables:
###############################################################################

export LIBXULSWORD_MAJOR=1
export LIBXULSWORD_MINOR=5
export LIBXULSWORD_REVIS=6

if [[ -z "$LIBXULSWORD_ONLY" ]]; then
  export LIBXULSWORD_ONLY=no
fi

if [ -e /vagrant ]; then export CONTEXT="guest"; else export CONTEXT="host"; fi
export XULSWORD="$( pwd -P )"
export CPP="$XULSWORD/Cpp"
export LIBXULSWORD="$XULSWORD/build/app/node_modules/libxulsword"

# Set WINMACHINE to x86 or x64 to compile Windows 32 bit or 64 bit, respectively.
# Or set to 'no' to skip compile for windows.
export WINMACHINE=no
export TOOLCHAIN_PREFIX=i686-w64-mingw32
export ADDRESS_MODEL=32
if [ "$WINMACHINE" = "x64" ]; then
  export ADDRESS_MODEL=64
  export TOOLCHAIN_PREFIX=x86_64-w64-mingw32
fi

export XCWD="${ADDRESS_MODEL}win"

# The ming-gcc cross-compiler standard must be 'posix' to work with NodeAPI:
export GCCSTD=posix
