#!/bin/bash

export GYP_CROSSCOMPILE=1

export CC_target=/usr/bin/x86_64-w64-mingw32-gcc
export CXX_target=/usr/bin/x86_64-w64-mingw32-g++ 
export LD_target=/usr/bin/x86_64-w64-mingw32-ld 
export AR_target=/usr/bin/x86_64-w64-mingw32-ar 
export AS_target=/usr/bin/x86_64-w64-mingw32-as 

